# Generated by Django 5.2.7 on 2025-11-02 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='category',
            field=models.CharField(blank=True, choices=[('Street Maintenance', 'Street Maintenance'), ('Trash Services', 'Trash Services'), ('Water Utilities', 'Water Utilities'), ('Animal Control', 'Animal Control'), ('Electrical Utilities', 'Electrical Utilities'), ('etc.', 'etc.')], max_length=100, null=True),
        ),
    ]
