# Generated by Django 5.2.7 on 2025-11-02 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_ticket_resolved'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='resolution_comment',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
